#!/bin/bash

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

export CHARSET=UTF-8
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PAGER=less

umask 022

# Load our starter scripts if any
for script in /etc/profile.d/*.sh ; do
        if [ -r $script ] ; then
                . $script
        fi
done

# Load our .bashrc if found
if [[ -f "~/.bashrc" ]]; then
    . ~/.bashrc
elif [[ -f "/etc/bashrc" ]]; then
    . /etc/bashrc
fi
